namespace Trains.Model.Entities
{
	public enum TrainClass
	{
		INTERNATIONAL = 0,
		INTERREGIONALBUSINESS = 1,
		INTERREGIONALECONOM = 2,
		REGIONALBUSINESS = 3,
		REGIONALECONOM = 4,
		CITY = 5,
		FOREIGN = 6
	}

	public enum Carriage
	{
		FIRSTCLASSSLEEPER = 0,
		COMPARTMENTSLEEPER = 1,
		ECONOMYCLASSSLEEPER = 2,
		SEATINGCOACHES1 = 3,
		SEATINGCOACHES2 = 4,
		MULTIPLEUNITCARS1 = 5,
		MULTIPLEUNITCARS2 = 6,
		MULTIPLEUNITCOACH = 7
	}

	public enum AboutPicture
	{
		MARKET = 0,
		SETTINGS = 1,
		MAIL = 2,
		ABOUTAPP = 3,
		SHARE = 4
	}
	public enum ShareSocial
	{
		VKONTAKTE = 0,
		FACEBOOK = 1,
		TWITTER = 2,
		LINKEDIN = 3,
		GOOGLEPLUS = 4,
		ODNOKLASSNIKI = 5
	}
}
