//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Trains.Resources {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class ru_RU {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ru_RU() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("Trains.Resources.ru-RU", typeof(ru_RU).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список ваших маршрутов теперь пуст.
        /// </summary>
        internal static string AllFavoritesDeleted {
            get {
                return ResourceManager.GetString("AllFavoritesDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправление: .
        /// </summary>
        internal static string Arrival {
            get {
                return ResourceManager.GetString("Arrival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Беларусь).
        /// </summary>
        internal static string BelarusConstString {
            get {
                return ResourceManager.GetString("BelarusConstString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to бизнес.
        /// </summary>
        internal static string Business {
            get {
                return ResourceManager.GetString("Business", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверьте подключение к интернету.
        /// </summary>
        internal static string ConectionError {
            get {
                return ResourceManager.GetString("ConectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск может производится только за 45 дней от текущего момента или используйте режим &apos;На все дни&apos;.
        /// </summary>
        internal static string DateTooBig {
            get {
                return ResourceManager.GetString("DateTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск может производится начиная от текущего времени.
        /// </summary>
        internal static string DateUpTooLater {
            get {
                return ResourceManager.GetString("DateUpTooLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прибытие: .
        /// </summary>
        internal static string Departure {
            get {
                return ResourceManager.GetString("Departure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохраните хотя бы один маршрут, что бы иметь возможность редактирования.
        /// </summary>
        internal static string EditFavoriteMessageError {
            get {
                return ResourceManager.GetString("EditFavoriteMessageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не найден последний запрос, или произошла ошибка загрузки.
        /// </summary>
        internal static string ErrorUpdate {
            get {
                return ResourceManager.GetString("ErrorUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to everyday.
        /// </summary>
        internal static string Everyday {
            get {
                return ResourceManager.GetString("Everyday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш список пуст.
        /// </summary>
        internal static string FavoriteListIsEmpthy {
            get {
                return ResourceManager.GetString("FavoriteListIsEmpthy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ч. .
        /// </summary>
        internal static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Один или оба пункта не существует, проверьте еще раз ввод.
        /// </summary>
        internal static string IncorrectInput {
            get {
                return ResourceManager.GetString("IncorrectInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Международные.
        /// </summary>
        internal static string International {
            get {
                return ResourceManager.GetString("International", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доступ к интернету отсутствует, проверьте подключение!.
        /// </summary>
        internal static string InternetConnectionError {
            get {
                return ResourceManager.GetString("InternetConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Межрегиональные.
        /// </summary>
        internal static string Interregional {
            get {
                return ResourceManager.GetString("Interregional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Успешно обновлен язык! Просьба перезайти в приложение!.
        /// </summary>
        internal static string LanguageChanged {
            get {
                return ResourceManager.GetString("LanguageChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  мин..
        /// </summary>
        internal static string Min {
            get {
                return ResourceManager.GetString("Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to нет.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мест нет. Уточняйте в кассах.
        /// </summary>
        internal static string NoPlace {
            get {
                return ResourceManager.GetString("NoPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите интересующие вас станции, затем выберите кнопку удалить выбранные.
        /// </summary>
        internal static string NotifyMessage {
            get {
                return ResourceManager.GetString("NotifyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все дни.
        /// </summary>
        internal static string OnAllDays {
            get {
                return ResourceManager.GetString("OnAllDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На дату.
        /// </summary>
        internal static string OnDay {
            get {
                return ResourceManager.GetString("OnDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мест: .
        /// </summary>
        internal static string Place {
            get {
                return ResourceManager.GetString("Place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мест нет .
        /// </summary>
        internal static string PlaceNo {
            get {
                return ResourceManager.GetString("PlaceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Места есть .
        /// </summary>
        internal static string PlaceYes {
            get {
                return ResourceManager.GetString("PlaceYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Одна или обе станции не введены.
        /// </summary>
        internal static string PointsIsInCorrect {
            get {
                return ResourceManager.GetString("PointsIsInCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to цена: .
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Региональные.
        /// </summary>
        internal static string Regional {
            get {
                return ResourceManager.GetString("Regional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Маршрут добавлен!.
        /// </summary>
        internal static string RouteIsAddedToFavorite {
            get {
                return ResourceManager.GetString("RouteIsAddedToFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Станция удалена!.
        /// </summary>
        internal static string RouteIsDeletedInFavorite {
            get {
                return ResourceManager.GetString("RouteIsDeletedInFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Маршрут не найден, проверьте поля ввода станций!.
        /// </summary>
        internal static string RouteIsIncorect {
            get {
                return ResourceManager.GetString("RouteIsIncorect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошел сбой при загрузке данных, при продолжительном сбое просьба уведомить нас.
        /// </summary>
        internal static string SearchError {
            get {
                return ResourceManager.GetString("SearchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сидячий.
        /// </summary>
        internal static string Sessile {
            get {
                return ResourceManager.GetString("Sessile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уточните дату для отображения информации о местах.
        /// </summary>
        internal static string SpecifyDate {
            get {
                return ResourceManager.GetString("SpecifyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стоянка: .
        /// </summary>
        internal static string Stay {
            get {
                return ResourceManager.GetString("Stay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данный маршрут уже присутствует.
        /// </summary>
        internal static string ThisRouteIsPresent {
            get {
                return ResourceManager.GetString("ThisRouteIsPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сегодня.
        /// </summary>
        internal static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завтра.
        /// </summary>
        internal static string tommorow {
            get {
                return ResourceManager.GetString("tommorow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поезда на дату отправления не найдены.
        /// </summary>
        internal static string TrainsNotFound {
            get {
                return ResourceManager.GetString("TrainsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to неограничено.
        /// </summary>
        internal static string Unlimited {
            get {
                return ResourceManager.GetString("Unlimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to через .
        /// </summary>
        internal static string Via {
            get {
                return ResourceManager.GetString("Via", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вчера.
        /// </summary>
        internal static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }
    }
}
