#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Trains.Droid.Resource", IsApplication=true)]

namespace Trains.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Chance.MvvmCross.Plugins.UserInteraction.Droid.Resource.String.library_name = global::Trains.Droid.Resource.String.library_name;
			global::Cirrious.MvvmCross.Plugins.Network.Droid.Resource.String.ApplicationName = global::Trains.Droid.Resource.String.ApplicationName;
			global::Cirrious.MvvmCross.Plugins.Network.Droid.Resource.String.Hello = global::Trains.Droid.Resource.String.Hello;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f080000
			public const int planets_array = 2131230720;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int MvxBind = 2130771968;
			
			// aapt resource value: 0x7f010004
			public const int MvxDropDownItemTemplate = 2130771972;
			
			// aapt resource value: 0x7f010003
			public const int MvxItemTemplate = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int MvxLang = 2130771969;
			
			// aapt resource value: 0x7f010005
			public const int MvxSource = 2130771973;
			
			// aapt resource value: 0x7f010002
			public const int MvxTemplate = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f07000a
			public const int black = 2131165194;
			
			// aapt resource value: 0x7f070000
			public const int blue = 2131165184;
			
			// aapt resource value: 0x7f070005
			public const int darkblue = 2131165189;
			
			// aapt resource value: 0x7f070007
			public const int darkgreen = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int darkorange = 2131165192;
			
			// aapt resource value: 0x7f070006
			public const int darkpurple = 2131165190;
			
			// aapt resource value: 0x7f070009
			public const int darkred = 2131165193;
			
			// aapt resource value: 0x7f070002
			public const int green = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int orange = 2131165187;
			
			// aapt resource value: 0x7f070001
			public const int purple = 2131165185;
			
			// aapt resource value: 0x7f070004
			public const int red = 2131165188;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int borderDark = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int borderLight = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int circle_shape = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int circular_progress_bar = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int CompartmentSleeper = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int EconomyClassSleeper = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int FirstClassSleeper = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int GE = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_action_about = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_action_import_export = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_action_important = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_action_not_important = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic_action_refresh = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int Icon = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int IL = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int IRLB_IRLE = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int MultipleUnitCars1 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int MultipleUnitCars2 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int MultipleUnitCoach = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int RLB_RLE = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int SeatingCoaches1 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int SeatingCoaches2 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int splash = 2130837526;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f04000a
			public const int FromTextView = 2130968586;
			
			// aapt resource value: 0x7f040000
			public const int MvxBindingTagUnique = 2130968576;
			
			// aapt resource value: 0x7f040008
			public const int SearchDate = 2130968584;
			
			// aapt resource value: 0x7f04000c
			public const int SearchTrain = 2130968588;
			
			// aapt resource value: 0x7f040009
			public const int SearchType = 2130968585;
			
			// aapt resource value: 0x7f040007
			public const int StopPointsListView = 2130968583;
			
			// aapt resource value: 0x7f04000b
			public const int ToTextView = 2130968587;
			
			// aapt resource value: 0x7f040019
			public const int about = 2130968601;
			
			// aapt resource value: 0x7f04001b
			public const int favorite = 2130968603;
			
			// aapt resource value: 0x7f040015
			public const int help = 2130968597;
			
			// aapt resource value: 0x7f040001
			public const int imageview = 2130968577;
			
			// aapt resource value: 0x7f040017
			public const int mail = 2130968599;
			
			// aapt resource value: 0x7f040012
			public const int mainMenu = 2130968594;
			
			// aapt resource value: 0x7f040006
			public const int progressBar = 2130968582;
			
			// aapt resource value: 0x7f040016
			public const int rate = 2130968598;
			
			// aapt resource value: 0x7f040011
			public const int resetbutton = 2130968593;
			
			// aapt resource value: 0x7f04001a
			public const int reverseSearch = 2130968602;
			
			// aapt resource value: 0x7f04000e
			public const int routes = 2130968590;
			
			// aapt resource value: 0x7f040018
			public const int settings = 2130968600;
			
			// aapt resource value: 0x7f040010
			public const int spinner = 2130968592;
			
			// aapt resource value: 0x7f040014
			public const int swap = 2130968596;
			
			// aapt resource value: 0x7f040002
			public const int tab1 = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int tab2 = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int tab3 = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int textView2 = 2130968581;
			
			// aapt resource value: 0x7f04000d
			public const int textView3 = 2130968589;
			
			// aapt resource value: 0x7f04001c
			public const int unFavorite = 2130968604;
			
			// aapt resource value: 0x7f040013
			public const int update = 2130968595;
			
			// aapt resource value: 0x7f04000f
			public const int vertical_line = 2130968591;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AboutView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CarriageView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int EditFavoriteRoutesView = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int HelpView = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int informationaltemplate = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int InformationView = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int lastroutetemplate = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int MainView = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int placetemplate = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int routestemplate = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int scheduletemplate = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int ScheduleView = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int SettingsView = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int SplashScreen = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int stoppointstemplate = 2130903054;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f090000
			public const int main_menu = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int schedule_menu = 2131296257;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int Search = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int library_name = 2131099651;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050002
			public const int HelpTrainImage = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int PlaceClasses = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBinding = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[] {
					2130771970};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxImageView = new int[] {
					2130771973};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130771971,
					2130771972};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
