#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Trains.Droid.Resource", IsApplication=true)]

namespace Trains.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Chance.MvvmCross.Plugins.UserInteraction.Droid.Resource.String.library_name = global::Trains.Droid.Resource.String.library_name;
			global::Cirrious.MvvmCross.Plugins.Network.Droid.Resource.String.ApplicationName = global::Trains.Droid.Resource.String.ApplicationName;
			global::Cirrious.MvvmCross.Plugins.Network.Droid.Resource.String.Hello = global::Trains.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int MvxBind = 2130771968;
			
			// aapt resource value: 0x7f010004
			public const int MvxDropDownItemTemplate = 2130771972;
			
			// aapt resource value: 0x7f010003
			public const int MvxItemTemplate = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int MvxLang = 2130771969;
			
			// aapt resource value: 0x7f010005
			public const int MvxSource = 2130771973;
			
			// aapt resource value: 0x7f010002
			public const int MvxTemplate = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int splash = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040005
			public const int FromTextView = 2130968581;
			
			// aapt resource value: 0x7f040000
			public const int MvxBindingTagUnique = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int SearchDate = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int SearchType = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int ToTextView = 2130968582;
			
			// aapt resource value: 0x7f04000b
			public const int button2 = 2130968587;
			
			// aapt resource value: 0x7f040007
			public const int button3 = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int button4 = 2130968584;
			
			// aapt resource value: 0x7f040001
			public const int tab1 = 2130968577;
			
			// aapt resource value: 0x7f04000a
			public const int tab2 = 2130968586;
			
			// aapt resource value: 0x7f04000c
			public const int tab3 = 2130968588;
			
			// aapt resource value: 0x7f040002
			public const int textView2 = 2130968578;
			
			// aapt resource value: 0x7f040009
			public const int textView3 = 2130968585;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AboutView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int EditFavoriteRoutesView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int HelpView = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int InformationView = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ItemView = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int MainView = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int ScheduleView = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int SettingsView = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int SplashScreen = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int Search = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int library_name = 2131099651;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBinding = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[] {
					2130771970};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxImageView = new int[] {
					2130771973};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130771971,
					2130771972};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
